# Generated by Django 2.2.12 on 2022-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='产品名')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='零售价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在售')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
