# Generated by Django 2.2.12 on 2022-05-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220413_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.IntegerField(default=1, verbose_name='目录id'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags_id',
            field=models.IntegerField(default=1, verbose_name='标签id'),
        ),
    ]
