# Generated by Django 2.2.12 on 2022-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=100, verbose_name='评论')),
                ('sale', models.DecimalField(decimal_places=2, default='', max_digits=11, verbose_name='售价')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='GetAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=50, verbose_name='地址')),
                ('phone_number', models.CharField(default='', max_length=11, verbose_name='买家电话号码')),
                ('name', models.CharField(default='', max_length=20, verbose_name='买家名字')),
            ],
        ),
        migrations.CreateModel(
            name='Info_deliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertise', models.TextField(default='', max_length=200, verbose_name='推荐广告')),
            ],
        ),
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=50, verbose_name='外卖名字')),
                ('delivery_info', models.BooleanField(default=False, verbose_name='是否到达')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='浙江', max_length=50, verbose_name='省份')),
                ('city', models.CharField(default='杭州', max_length=50, verbose_name='城市')),
                ('address', models.CharField(default='浙江工商大学', max_length=100, verbose_name='地址')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
