# Generated by Django 2.2.12 on 2022-05-29 02:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20220414_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressinfo',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='default_addr',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='detail_addr',
            field=models.CharField(default='浙江工商大学下沙校区', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='district',
            field=models.CharField(default='钱塘区', max_length=10),
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='latitiude',
            field=models.CharField(default='10.11', max_length=20),
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='longtitude',
            field=models.CharField(default='10.11', max_length=20),
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='street',
            field=models.CharField(default='白杨街道', max_length=20),
        ),
    ]
