# Generated by Django 2.2.12 on 2022-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20220529_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressinfo',
            name='default_addr',
        ),
        migrations.RemoveField(
            model_name='useraddressinfo',
            name='latitiude',
        ),
        migrations.RemoveField(
            model_name='useraddressinfo',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='phone',
            field=models.CharField(default='17816733515', max_length=20, verbose_name='手机号'),
        ),
    ]
