# Generated by Django 2.2.12 on 2022-05-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20220531_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='useraddressinfo',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
