# Generated by Django 2.2.12 on 2022-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20220531_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressinfo',
            name='name',
            field=models.CharField(default='胡路涯', max_length=20, verbose_name='名字'),
        ),
    ]
