# Generated by Django 2.2.12 on 2022-06-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_useraddressinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.IntegerField(default=0, verbose_name='商家Id')),
                ('foodId', models.CharField(default='', max_length=30, verbose_name='食物Id')),
                ('FoodName', models.CharField(default='', max_length=30, verbose_name='食物名称')),
                ('taste', models.CharField(default='', max_length=50, verbose_name='口味选择')),
                ('saleNum', models.CharField(default='', max_length=20, verbose_name='销量')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('count', models.IntegerField(default=0, verbose_name='计数')),
                ('foodPic', models.CharField(max_length=100, verbose_name='图片地址')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=30, verbose_name='店铺名')),
                ('saleNum', models.IntegerField(default=0, verbose_name='销量')),
                ('offerPrice', models.IntegerField(default=0, verbose_name='提供的价格')),
                ('distributionCost', models.IntegerField(default=0, verbose_name='分配费用')),
                ('welfare', models.CharField(max_length=50, verbose_name='福利')),
                ('time', models.CharField(max_length=30, verbose_name='配送时间')),
                ('shopPic', models.CharField(max_length=100, verbose_name='图片地址')),
                ('shopNotice', models.CharField(max_length=100, verbose_name='公告')),
            ],
        ),
    ]
