# Generated by Django 2.2.12 on 2022-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_food_list_shop_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='book_info',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='book_info',
            name='sale',
        ),
        migrations.AddField(
            model_name='book_info',
            name='_iphone',
            field=models.CharField(default='17816733515', max_length=100, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='发货时间'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='money',
            field=models.CharField(default='441', max_length=50, verbose_name='订单发价'),
        ),
        migrations.AddField(
            model_name='book_info',
            name='shop',
            field=models.CharField(default='蛋糕店', max_length=100, verbose_name='店铺'),
        ),
    ]
