# Generated by Django 2.2.12 on 2022-06-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20220604_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_info',
            old_name='shop',
            new_name='shopname',
        ),
    ]
