# Generated by Django 2.2.12 on 2022-06-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20220604_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='describations',
            field=models.CharField(default='有点甜', max_length=100, verbose_name='评价'),
        ),
    ]
