# Generated by Django 2.2.12 on 2022-06-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_book_info_describations'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressinfo',
            name='real_id',
            field=models.CharField(default='1', max_length=20, verbose_name='真实id'),
        ),
    ]
