# Generated by Django 2.2.12 on 2022-05-29 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220416_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='join_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='salt',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_photo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
